# 网页标题
title: fbunch
# 网页描述（显示在标题下方）
description: 一个用来进行Bunching分析的Stata命令

# --- 主题选择 ---
theme: jekyll-theme-minima

# --- 设置 markdown 渲染引擎 ---
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
